### ISSUE TITLE
Application sometimes crashes when XMPP message is sent

### ISSUE THREAD

**Issue by livthomas** [dhis2msg/DHISmessenger#24]
When you send messages in a group conversation, the application sometimes crashes. This bug might have been introduced by my last commit c94ca83330d9ad80513bf0e29cf6f652711cd670 where I ignored running some operations on UI thread.

```
java.lang.IllegalStateException: The content of the adapter has changed but ListView did not receive a notification. Make sure the content of your adapter is not modified from a background thread, but only from the UI thread. Make sure your adapter calls notifyDataSetChanged() when its content changes. [in ListView(2131558570, class android.widget.ListView) with Adapter(class org.dhis2.messenger.gui.adapter.IMChatAdapter)]
    at android.widget.ListView.layoutChildren(ListView.java:1566)
    at android.widget.AbsListView.onLayout(AbsListView.java:2564)
    at android.view.View.layout(View.java:15749)
    at android.view.ViewGroup.layout(ViewGroup.java:4880)
    at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1055)
    at android.view.View.layout(View.java:15749)
    at android.view.ViewGroup.layout(ViewGroup.java:4880)
    at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
    at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
    at android.view.View.layout(View.java:15749)
    at android.view.ViewGroup.layout(ViewGroup.java:4880)
    at com.android.internal.widget.ActionBarOverlayLayout.onLayout(ActionBarOverlayLayout.java:459)
    at android.view.View.layout(View.java:15749)
    at android.view.ViewGroup.layout(ViewGroup.java:4880)
    at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
    at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
    at android.view.View.layout(View.java:15749)
    at android.view.ViewGroup.layout(ViewGroup.java:4880)
    at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2358)
    at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2071)
    at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1256)
    at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6635)
    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:813)
    at android.view.Choreographer.doCallbacks(Choreographer.java:613)
    at android.view.Choreographer.doFrame(Choreographer.java:583)
    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:799)
    at android.os.Handler.handleCallback(Handler.java:733)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:146)
    at android.app.ActivityThread.main(ActivityThread.java:5593)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:515)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
    at dalvik.system.NativeStart.main(Native Method)
```

**Comment by livthomas** [comment]
The bug was not introduced by us but had been present in the application before.
